services:
  api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    container_name: itinerary-api
    ports:
      - "8000:8000"

    environment:
      OSRM_URL_CAR: http://osrm-car:5000
      OSRM_URL_BIKE: http://osrm-bike:5000
      OSRM_URL_FOOT: http://osrm-foot:5000

      POSTGRES_HOST: ${POSTGRES_VACANCES_HOST}
      POSTGRES_PORT: ${POSTGRES_VACANCES_PORT}
      POSTGRES_DB: ${POSTGRES_VACANCES_DB}
      POSTGRES_USER: ${POSTGRES_VACANCES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_VACANCES_PASSWORD}

    volumes:
      - ../../app:/app/app:rw
      - ../../logs:/app/logs:rw

    networks:
      - vacances-network

networks:
  vacances-network:
    external: true