events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        # DRIVING (voiture)
        location /route/v1/driving  { proxy_pass http://osrm-car:5000; }
        location /table/v1/driving  { proxy_pass http://osrm-car:5000; }

        # BIKE (vélo)
        location /route/v1/bike     { proxy_pass http://osrm-bike:5000; }
        location /table/v1/bike     { proxy_pass http://osrm-bike:5000; }

        # FOOT (marche)
        location /route/v1/foot     { proxy_pass http://osrm-foot:5000; }
        location /table/v1/foot     { proxy_pass http://osrm-foot:5000; }

        # Tout le reste = erreur
        location / {
            add_header Content-Type text/plain;
            return 404 'Profile not supported. Use: driving, bike, or foot';
        }
    }
}
