services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: vacances
      POSTGRES_PASSWORD: vacances
      POSTGRES_DB: vacances
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vacances-network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - vacances-network

  # Prometheus - Collecteur de métriques
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: promethes
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - vacances-network

  # Grafana - Visualisation des métriques
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard-grafana-tripmango-overview
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - vacances-network
    depends_on:
      - prometheus

  # OSRM Exporter
  osrm-exporter:
    build:
      context: ./osrm-exporter/
      dockerfile: Dockerfile
    container_name: osrm-exporter
    ports:
      - "8001:8001"
    environment:
      - OSRM_CAR_URL=http://osrm-car:5000
      - OSRM_BIKE_URL=http://osrm-bike:5000
      - OSRM_FOOT_URL=http://osrm-foot:5000
    restart: unless-stopped
    networks:
      - vacances-network
    depends_on:
      - prometheus
  
  # postgres exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://vacances:vacances@postgres:5432/vacances?sslmode=disable"
    networks:
      - vacances-network
    depends_on:
      - postgres

volumes:
  prometheus-data:
  grafana-data:
  postgres-data:

networks:
  vacances-network:
    external: true